# Generated by Django 3.1.7 on 2021-04-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='time',
            field=models.TimeField(blank=True, verbose_name='Время уведомления'),
        ),
    ]
