# Generated by Django 3.1.7 on 2021-04-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210406_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminders',
            name='is_notificated',
            field=models.BooleanField(default=False, verbose_name='Напоминание отправлено?'),
        ),
    ]
